<?php
/**
 * APIApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Encompass Supply Chain Solutions
 *
 * Services require a user name and password that must be obtained from Encompass.  We issue a single set of credentials for all invironments.  Please make sure you are pointing to the correct endpoint described in the __servers__ section.  Services all return the elements `status->errorCode` and `status->errorMessage`.  Successful reqeusts will return a __100__ `errorCode`.   If you have any questions that are not answered here or would like to discuss the overall process, please contact your account rep to schedule a technical call.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * APIApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class APIApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for restfulserviceBrandListPost
     *
     * Brand List.
     *
     */
    public function testRestfulserviceBrandListPost()
    {
    }

    /**
     * Test case for restfulserviceCreateOrderPost
     *
     * Create an Order.
     *
     */
    public function testRestfulserviceCreateOrderPost()
    {
    }

    /**
     * Test case for restfulserviceExplodedViewListAssembliesPost
     *
     * View assemblies list for interactive exploded views.
     *
     */
    public function testRestfulserviceExplodedViewListAssembliesPost()
    {
    }

    /**
     * Test case for restfulserviceExplodedViewViewAssemblyPost
     *
     * View assembly for interactive exploded views..
     *
     */
    public function testRestfulserviceExplodedViewViewAssemblyPost()
    {
    }

    /**
     * Test case for restfulserviceFrequentlyPurchasedPartsPost
     *
     * Frequently Purchased Parts.
     *
     */
    public function testRestfulserviceFrequentlyPurchasedPartsPost()
    {
    }

    /**
     * Test case for restfulserviceModelPartListPost
     *
     * Model Part List.
     *
     */
    public function testRestfulserviceModelPartListPost()
    {
    }

    /**
     * Test case for restfulservicePartsInformationPost
     *
     * Parts Information.
     *
     */
    public function testRestfulservicePartsInformationPost()
    {
    }

    /**
     * Test case for restfulserviceSearchPost
     *
     * Search.
     *
     */
    public function testRestfulserviceSearchPost()
    {
    }
}
