<?php
/**
 * InlineResponse452DataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Encompass Supply Chain Solutions
 *
 * Services require a user name and password that must be obtained from Encompass.  We issue a single set of credentials for all invironments.  Please make sure you are pointing to the correct endpoint described in the __servers__ section.  Services all return the elements `status->errorCode` and `status->errorMessage`.  Successful reqeusts will return a __100__ `errorCode`.   If you have any questions that are not answered here or would like to discuss the overall process, please contact your account rep to schedule a technical call.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse452DataTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse452Data
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse452DataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse452Data"
     */
    public function testInlineResponse452Data()
    {
    }

    /**
     * Test attribute "variation_name"
     */
    public function testPropertyVariationName()
    {
    }

    /**
     * Test attribute "variation_image"
     */
    public function testPropertyVariationImage()
    {
    }

    /**
     * Test attribute "variations"
     */
    public function testPropertyVariations()
    {
    }

    /**
     * Test attribute "service_manual_url"
     */
    public function testPropertyServiceManualUrl()
    {
    }

    /**
     * Test attribute "exploded_view_url"
     */
    public function testPropertyExplodedViewUrl()
    {
    }

    /**
     * Test attribute "small_image_url"
     */
    public function testPropertySmallImageUrl()
    {
    }
}
