<?php
/**
 * InlineResponse4006StatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Encompass Supply Chain Solutions
 *
 * Services require a user name and password that must be obtained from Encompass.  We issue a single set of credentials for all invironments.  Please make sure you are pointing to the correct endpoint described in the __servers__ section.  Services all return the elements `status->errorCode` and `status->errorMessage`.  Successful reqeusts will return a __100__ `errorCode`.   If you have any questions that are not answered here or would like to discuss the overall process, please contact your account rep to schedule a technical call.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse4006StatusTest Class Doc Comment
 *
 * @category    Class
 * @description |errorCode|errorMessage| |-------|--------| |-200|files did not open (host issue)| |-201|invalid jsonUser| |-202|invalid customer number from customer cross| |-203|customer number is required| |-204|invalid customer number| |-205|referenceNumber1 is required| |-206|duplicate referenceNumber1| |-207|transactionID is required| |-208|invalid part| |-209|invalid pid| |-210|has a substitute part| |-211|an invalid orderQuantity| |-212|has a minimum order qty| |-213|no valid parts were submitted| |-214|is not available for backorder| |-215|is not available for resale| |-216|is not available for country| |-217|account does not allow backorder| |-218|n/a| |-219|n/a| |-220|requires manufacturer authorization in authorizationOrReferenceNumber| |-221|n/a| |-222|Invalid shipToCountryCode| |-223|requires shipToState for country| |-224|Invalid shipToState| |-225|Invalid shippingThirdPartyCarrier| |-226|account has been closed| |-227|Invalid shippingThirdPartyNumber| |-228|Invalid shipToPhone| |-229|password is required| |-230|password is invalid| |-231|Invalid claimsProcessorCode or claimNumber|
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse4006StatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse4006Status"
     */
    public function testInlineResponse4006Status()
    {
    }

    /**
     * Test attribute "error_code"
     */
    public function testPropertyErrorCode()
    {
    }

    /**
     * Test attribute "error_message"
     */
    public function testPropertyErrorMessage()
    {
    }
}
