<?php
/**
 * InlineResponse2005DataPartsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Encompass Supply Chain Solutions
 *
 * Services require a user name and password that must be obtained from Encompass.  We issue a single set of credentials for all invironments.  Please make sure you are pointing to the correct endpoint described in the __servers__ section.  Services all return the elements `status->errorCode` and `status->errorMessage`.  Successful reqeusts will return a __100__ `errorCode`.   If you have any questions that are not answered here or would like to discuss the overall process, please contact your account rep to schedule a technical call.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse2005DataPartsTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2005DataParts
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2005DataPartsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2005DataParts"
     */
    public function testInlineResponse2005DataParts()
    {
    }

    /**
     * Test attribute "base_pn"
     */
    public function testPropertyBasePn()
    {
    }

    /**
     * Test attribute "mfg_code"
     */
    public function testPropertyMfgCode()
    {
    }

    /**
     * Test attribute "mfg_name"
     */
    public function testPropertyMfgName()
    {
    }

    /**
     * Test attribute "part_number"
     */
    public function testPropertyPartNumber()
    {
    }

    /**
     * Test attribute "part_description"
     */
    public function testPropertyPartDescription()
    {
    }

    /**
     * Test attribute "detailed_part_description"
     */
    public function testPropertyDetailedPartDescription()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "length"
     */
    public function testPropertyLength()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "hts_code"
     */
    public function testPropertyHtsCode()
    {
    }

    /**
     * Test attribute "carrier_size"
     */
    public function testPropertyCarrierSize()
    {
    }

    /**
     * Test attribute "authorization_required"
     */
    public function testPropertyAuthorizationRequired()
    {
    }

    /**
     * Test attribute "availability"
     */
    public function testPropertyAvailability()
    {
    }

    /**
     * Test attribute "availability_by_location"
     */
    public function testPropertyAvailabilityByLocation()
    {
    }

    /**
     * Test attribute "eta"
     */
    public function testPropertyEta()
    {
    }

    /**
     * Test attribute "list_price"
     */
    public function testPropertyListPrice()
    {
    }

    /**
     * Test attribute "core_price"
     */
    public function testPropertyCorePrice()
    {
    }

    /**
     * Test attribute "part_price"
     */
    public function testPropertyPartPrice()
    {
    }

    /**
     * Test attribute "total_price"
     */
    public function testPropertyTotalPrice()
    {
    }

    /**
     * Test attribute "sub_part"
     */
    public function testPropertySubPart()
    {
    }

    /**
     * Test attribute "allow_rts"
     */
    public function testPropertyAllowRts()
    {
    }

    /**
     * Test attribute "allow_iwr"
     */
    public function testPropertyAllowIwr()
    {
    }

    /**
     * Test attribute "small_image_url"
     */
    public function testPropertySmallImageUrl()
    {
    }

    /**
     * Test attribute "compatible_models"
     */
    public function testPropertyCompatibleModels()
    {
    }
}
