<?php
/**
 * RestfulserviceModelPartListPost452ResponseData
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Encompass\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Encompass Supply Chain Solutions
 *
 * Services require a user name and password that must be obtained from Encompass.  We issue a single set of credentials for all invironments.  Please make sure you are pointing to the correct endpoint described in the __servers__ section.  Services all return the elements `status->errorCode` and `status->errorMessage`.  Successful reqeusts will return a __100__ `errorCode`.   If you have any questions that are not answered here or would like to discuss the overall process, please contact your account rep to schedule a technical call.
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Encompass\SDK\Model;

use \ArrayAccess;
use \Encompass\SDK\ObjectSerializer;

/**
 * RestfulserviceModelPartListPost452ResponseData Class Doc Comment
 *
 * @category Class
 * @package  Encompass\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RestfulserviceModelPartListPost452ResponseData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_restfulservice_modelPartList_post_452_response_data';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'variation_name' => 'string',
        'variation_image' => 'string',
        'variations' => 'object[]',
        'service_manual_url' => 'string',
        'exploded_view_url' => 'string',
        'small_image_url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'variation_name' => null,
        'variation_image' => null,
        'variations' => null,
        'service_manual_url' => null,
        'exploded_view_url' => null,
        'small_image_url' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'variation_name' => false,
        'variation_image' => false,
        'variations' => false,
        'service_manual_url' => false,
        'exploded_view_url' => false,
        'small_image_url' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'variation_name' => 'variationName',
        'variation_image' => 'variationImage',
        'variations' => 'variations',
        'service_manual_url' => 'serviceManualUrl',
        'exploded_view_url' => 'explodedViewUrl',
        'small_image_url' => 'smallImageURL'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'variation_name' => 'setVariationName',
        'variation_image' => 'setVariationImage',
        'variations' => 'setVariations',
        'service_manual_url' => 'setServiceManualUrl',
        'exploded_view_url' => 'setExplodedViewUrl',
        'small_image_url' => 'setSmallImageUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'variation_name' => 'getVariationName',
        'variation_image' => 'getVariationImage',
        'variations' => 'getVariations',
        'service_manual_url' => 'getServiceManualUrl',
        'exploded_view_url' => 'getExplodedViewUrl',
        'small_image_url' => 'getSmallImageUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('variation_name', $data ?? [], null);
        $this->setIfExists('variation_image', $data ?? [], null);
        $this->setIfExists('variations', $data ?? [], null);
        $this->setIfExists('service_manual_url', $data ?? [], null);
        $this->setIfExists('exploded_view_url', $data ?? [], null);
        $this->setIfExists('small_image_url', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets variation_name
     *
     * @return string|null
     */
    public function getVariationName()
    {
        return $this->container['variation_name'];
    }

    /**
     * Sets variation_name
     *
     * @param string|null $variation_name This will be what this manufacturer calls this modelVariation.  Some manufacturers use different names.
     *
     * @return self
     */
    public function setVariationName($variation_name)
    {
        if (is_null($variation_name)) {
            throw new \InvalidArgumentException('non-nullable variation_name cannot be null');
        }
        $this->container['variation_name'] = $variation_name;

        return $this;
    }

    /**
     * Gets variation_image
     *
     * @return string|null
     */
    public function getVariationImage()
    {
        return $this->container['variation_image'];
    }

    /**
     * Sets variation_image
     *
     * @param string|null $variation_image This image will show an example label to help the user find the correct information.
     *
     * @return self
     */
    public function setVariationImage($variation_image)
    {
        if (is_null($variation_image)) {
            throw new \InvalidArgumentException('non-nullable variation_image cannot be null');
        }
        $this->container['variation_image'] = $variation_image;

        return $this;
    }

    /**
     * Gets variations
     *
     * @return object[]|null
     */
    public function getVariations()
    {
        return $this->container['variations'];
    }

    /**
     * Sets variations
     *
     * @param object[]|null $variations array of model variations to pick from and send back to the service
     *
     * @return self
     */
    public function setVariations($variations)
    {
        if (is_null($variations)) {
            throw new \InvalidArgumentException('non-nullable variations cannot be null');
        }
        $this->container['variations'] = $variations;

        return $this;
    }

    /**
     * Gets service_manual_url
     *
     * @return string|null
     */
    public function getServiceManualUrl()
    {
        return $this->container['service_manual_url'];
    }

    /**
     * Sets service_manual_url
     *
     * @param string|null $service_manual_url 
     *
     * @return self
     */
    public function setServiceManualUrl($service_manual_url)
    {
        if (is_null($service_manual_url)) {
            throw new \InvalidArgumentException('non-nullable service_manual_url cannot be null');
        }
        $this->container['service_manual_url'] = $service_manual_url;

        return $this;
    }

    /**
     * Gets exploded_view_url
     *
     * @return string|null
     */
    public function getExplodedViewUrl()
    {
        return $this->container['exploded_view_url'];
    }

    /**
     * Sets exploded_view_url
     *
     * @param string|null $exploded_view_url 
     *
     * @return self
     */
    public function setExplodedViewUrl($exploded_view_url)
    {
        if (is_null($exploded_view_url)) {
            throw new \InvalidArgumentException('non-nullable exploded_view_url cannot be null');
        }
        $this->container['exploded_view_url'] = $exploded_view_url;

        return $this;
    }

    /**
     * Gets small_image_url
     *
     * @return string|null
     */
    public function getSmallImageUrl()
    {
        return $this->container['small_image_url'];
    }

    /**
     * Sets small_image_url
     *
     * @param string|null $small_image_url 
     *
     * @return self
     */
    public function setSmallImageUrl($small_image_url)
    {
        if (is_null($small_image_url)) {
            throw new \InvalidArgumentException('non-nullable small_image_url cannot be null');
        }
        $this->container['small_image_url'] = $small_image_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


