<?php
/**
 * RestfulserviceModelPartListPost200ResponseDataPartsInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Encompass\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Encompass Supply Chain Solutions
 *
 * Services require a user name and password that must be obtained from Encompass.  We issue a single set of credentials for all invironments.  Please make sure you are pointing to the correct endpoint described in the __servers__ section.  Services all return the elements `status->errorCode` and `status->errorMessage`.  Successful reqeusts will return a __100__ `errorCode`.   If you have any questions that are not answered here or would like to discuss the overall process, please contact your account rep to schedule a technical call.
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Encompass\SDK\Model;

use \ArrayAccess;
use \Encompass\SDK\ObjectSerializer;

/**
 * RestfulserviceModelPartListPost200ResponseDataPartsInner Class Doc Comment
 *
 * @category Class
 * @package  Encompass\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RestfulserviceModelPartListPost200ResponseDataPartsInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_restfulservice_modelPartList_post_200_response_data_parts_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'base_pn' => 'string',
        'mfg_code' => 'string',
        'mfg_name' => 'string',
        'part_number' => 'string',
        'part_description' => 'string',
        'category_description' => 'string',
        'demand' => 'string',
        'small_image_url' => 'string',
        'fix_percentage' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'base_pn' => null,
        'mfg_code' => null,
        'mfg_name' => null,
        'part_number' => null,
        'part_description' => null,
        'category_description' => null,
        'demand' => null,
        'small_image_url' => null,
        'fix_percentage' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'base_pn' => false,
        'mfg_code' => false,
        'mfg_name' => false,
        'part_number' => false,
        'part_description' => false,
        'category_description' => false,
        'demand' => false,
        'small_image_url' => false,
        'fix_percentage' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'base_pn' => 'basePN',
        'mfg_code' => 'mfgCode',
        'mfg_name' => 'mfgName',
        'part_number' => 'partNumber',
        'part_description' => 'partDescription',
        'category_description' => 'categoryDescription',
        'demand' => 'demand',
        'small_image_url' => 'smallImageURL',
        'fix_percentage' => 'fixPercentage'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'base_pn' => 'setBasePn',
        'mfg_code' => 'setMfgCode',
        'mfg_name' => 'setMfgName',
        'part_number' => 'setPartNumber',
        'part_description' => 'setPartDescription',
        'category_description' => 'setCategoryDescription',
        'demand' => 'setDemand',
        'small_image_url' => 'setSmallImageUrl',
        'fix_percentage' => 'setFixPercentage'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'base_pn' => 'getBasePn',
        'mfg_code' => 'getMfgCode',
        'mfg_name' => 'getMfgName',
        'part_number' => 'getPartNumber',
        'part_description' => 'getPartDescription',
        'category_description' => 'getCategoryDescription',
        'demand' => 'getDemand',
        'small_image_url' => 'getSmallImageUrl',
        'fix_percentage' => 'getFixPercentage'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('base_pn', $data ?? [], null);
        $this->setIfExists('mfg_code', $data ?? [], null);
        $this->setIfExists('mfg_name', $data ?? [], null);
        $this->setIfExists('part_number', $data ?? [], null);
        $this->setIfExists('part_description', $data ?? [], null);
        $this->setIfExists('category_description', $data ?? [], null);
        $this->setIfExists('demand', $data ?? [], null);
        $this->setIfExists('small_image_url', $data ?? [], null);
        $this->setIfExists('fix_percentage', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets base_pn
     *
     * @return string|null
     */
    public function getBasePn()
    {
        return $this->container['base_pn'];
    }

    /**
     * Sets base_pn
     *
     * @param string|null $base_pn 
     *
     * @return self
     */
    public function setBasePn($base_pn)
    {
        if (is_null($base_pn)) {
            throw new \InvalidArgumentException('non-nullable base_pn cannot be null');
        }
        $this->container['base_pn'] = $base_pn;

        return $this;
    }

    /**
     * Gets mfg_code
     *
     * @return string|null
     */
    public function getMfgCode()
    {
        return $this->container['mfg_code'];
    }

    /**
     * Sets mfg_code
     *
     * @param string|null $mfg_code 
     *
     * @return self
     */
    public function setMfgCode($mfg_code)
    {
        if (is_null($mfg_code)) {
            throw new \InvalidArgumentException('non-nullable mfg_code cannot be null');
        }
        $this->container['mfg_code'] = $mfg_code;

        return $this;
    }

    /**
     * Gets mfg_name
     *
     * @return string|null
     */
    public function getMfgName()
    {
        return $this->container['mfg_name'];
    }

    /**
     * Sets mfg_name
     *
     * @param string|null $mfg_name 
     *
     * @return self
     */
    public function setMfgName($mfg_name)
    {
        if (is_null($mfg_name)) {
            throw new \InvalidArgumentException('non-nullable mfg_name cannot be null');
        }
        $this->container['mfg_name'] = $mfg_name;

        return $this;
    }

    /**
     * Gets part_number
     *
     * @return string|null
     */
    public function getPartNumber()
    {
        return $this->container['part_number'];
    }

    /**
     * Sets part_number
     *
     * @param string|null $part_number 
     *
     * @return self
     */
    public function setPartNumber($part_number)
    {
        if (is_null($part_number)) {
            throw new \InvalidArgumentException('non-nullable part_number cannot be null');
        }
        $this->container['part_number'] = $part_number;

        return $this;
    }

    /**
     * Gets part_description
     *
     * @return string|null
     */
    public function getPartDescription()
    {
        return $this->container['part_description'];
    }

    /**
     * Sets part_description
     *
     * @param string|null $part_description 
     *
     * @return self
     */
    public function setPartDescription($part_description)
    {
        if (is_null($part_description)) {
            throw new \InvalidArgumentException('non-nullable part_description cannot be null');
        }
        $this->container['part_description'] = $part_description;

        return $this;
    }

    /**
     * Gets category_description
     *
     * @return string|null
     */
    public function getCategoryDescription()
    {
        return $this->container['category_description'];
    }

    /**
     * Sets category_description
     *
     * @param string|null $category_description 
     *
     * @return self
     */
    public function setCategoryDescription($category_description)
    {
        if (is_null($category_description)) {
            throw new \InvalidArgumentException('non-nullable category_description cannot be null');
        }
        $this->container['category_description'] = $category_description;

        return $this;
    }

    /**
     * Gets demand
     *
     * @return string|null
     */
    public function getDemand()
    {
        return $this->container['demand'];
    }

    /**
     * Sets demand
     *
     * @param string|null $demand 
     *
     * @return self
     */
    public function setDemand($demand)
    {
        if (is_null($demand)) {
            throw new \InvalidArgumentException('non-nullable demand cannot be null');
        }
        $this->container['demand'] = $demand;

        return $this;
    }

    /**
     * Gets small_image_url
     *
     * @return string|null
     */
    public function getSmallImageUrl()
    {
        return $this->container['small_image_url'];
    }

    /**
     * Sets small_image_url
     *
     * @param string|null $small_image_url 
     *
     * @return self
     */
    public function setSmallImageUrl($small_image_url)
    {
        if (is_null($small_image_url)) {
            throw new \InvalidArgumentException('non-nullable small_image_url cannot be null');
        }
        $this->container['small_image_url'] = $small_image_url;

        return $this;
    }

    /**
     * Gets fix_percentage
     *
     * @return float|null
     */
    public function getFixPercentage()
    {
        return $this->container['fix_percentage'];
    }

    /**
     * Sets fix_percentage
     *
     * @param float|null $fix_percentage 
     *
     * @return self
     */
    public function setFixPercentage($fix_percentage)
    {
        if (is_null($fix_percentage)) {
            throw new \InvalidArgumentException('non-nullable fix_percentage cannot be null');
        }
        $this->container['fix_percentage'] = $fix_percentage;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


